### ISSUE TITLE
Add-ons that only have development releases are not being updated

### ISSUE THREAD

**Issue by XLTechie** [josephsl/addonUpdater#10]
### STR:

1. Install an outdated development release of an add-on which does not have a stable release. For purposes of testing, I used [Becky V0.2](https://github.com/lukaszgo1/Becky/releases/download/V0.2-dev/Becky-0.2-dev.nvda-addon), by @lukaszgo1, since he reported the problem. Note that to successfully do this, I had to munge its manifest to claim lastTested was 2022.1.
2. For that add-on, select prefer development updates in Add-on Updater settings.
3. Info: That add-on is available via the addonFiles key "becky-dev".
4. Run an update check.

### Actual results:

No updates are found.

### Expected results:

The new version of Becky, V0.3, which is pointed to by addonFiles, should be found.

### Temporary solution:

Until we resolve this, I have placed an entry for "`becky`" (not "`becky-dev`", as its actual key appears), in the metadata database, and tested that it works to fool updater into thinking that a stable version exists, so that it then checks for the dev version.

### Long term solutions:

I think there are three directions possible:

1. Patch updater to pretend that dev versions with no stable versions, do have a stable version for purposes of updating. This is easy, but IMO there are already enough patchy situations in play.
2. Make official my temporary solution, and start adding dev versions with no stable versions to the database as fake stable entries. This requires on-going manual maintenance, but again, it is relatively easy, since there are few of these.
3. Add all dev versions to the metadata database, in a dev section, and refactor Updater to treat it like a separate list of add-ons that can be toggled between on an add-on by add-on basis.

We have talked about this third one before, but I think that limits the possibilities for update channels other than stable and dev, at least for now. Personally, that doesn't bother me.

**Comment by josephsl** [comment]
Hi,

Note: issues related to community add-ons metadata is closed as default add-on update source is NV Access add-on store which does take care of development releases.

Thanks.
