### ISSUE TITLE
Unable to check for updates for more add-ons in unknown circumstances, only WintenApps

### ISSUE THREAD

**Issue by cary-rowen** [josephsl/addonUpdater#18]
This issue was reported on the NVDA Chinese community.
The add-on update source is "China community add-ons catalog".
Of course, using the "NVDA community add-ons website" has the same result.
According to my observation, the problem can be solved by deleting `%appdata%\nvda\nvda3208.pickle`.
It is best to delete this file when NVDA is not running.

**Comment by josephsl** [comment]
Hi, I see. I think deleting the pickle file may not be the solution as it could be something else in code. A debug log is appreciated. Thanks.

**Comment by cary-rowen** [comment]
Hi @josephsl 
I've emailed you the debug level logs and pickle file privately.
grateful

**Comment by josephsl** [comment]
Hi,

Based on the debug log sent (privately), seems the issue has to do with the pickle file. I advise doing the following workarond:

1. Open NVDA user configuration folder.
2. Quit NVDA.
3. Delete nvda3208.pickle.
4. Start NVDA.

Also, note that the debug log says Add-on Updater 22.10, an unsupported version of the add-on - I support only the latest stable Add-on Updater version (23.03.4) at this time.

Thanks.

**Comment by josephsl** [comment]
Hi,

As a follow-up: it would be advisable to et some update sources updated based on recent changes to community add-ons update source json file with the introduction of NV Access add-on datastore.

Thanks.

**Comment by cary-rowen** [comment]
Hi,
Yes, my solution was also to delete nvda3208.pickle,
In addition, the addonsData.json and addonsUrl.json of the Chinese community are updated and merged from the following URL every day at 19:10:
* addonsData.json: https://nvdaaddons.github.io/data/addonsData.json
* addonsUrl.json: https://addons.nvda-project.org/files/get.php?addonslist
Thanks

**Comment by josephsl** [comment]
Hi, I see. I will keep this open in case a better solution is found or until Add-on Updater itself is declared end of maintenance. Thanks.

**Comment by josephsl** [comment]
Hi,

Note: issues related to add-ons metadata is closed as Add-on Updater features are frozen.

Thanks.
