### ISSUE TITLE
Prerelease add-ons: let users chose between beta and dev channels

### ISSUE THREAD

**Issue by josephsl** [josephsl/addonUpdater#19]
Hi,

With the upcoming NV Access add-on store, users can choose to install prerelease add-ons from either dev or beta channel. Previously only dev channel was supported as community add-ons repo supported only dev and stable channels. With the new add-on store, beta channel is introduced, equivalent to current dev channel (available to all NVDA channels, according to store docs). With some add-ons registered on add-on store released in beta channel, let Add-on Updater users choose which channel to subscribe to when installing prerelease builds.

Implementation: this involves:

1. Add an add-on channels key to add-on update state, a dictionary that maps add-on names to prerelease update channels. This key will house add-ons that are recorded inside dev updates list.
2. During update checks, set the update channel based on a combination of dev updates list and prerelease channels dictionary - if an add-on is part of dev updates list, see what the desired update channel is by looking up prelrease channels dictionary
3. Add an update channel combo box to Add-on Updater settings panel that will be enabled if the add-on selected from prefer development releases list is indeed checked (uses chdck list box), disabled otherwise.
4. Any add-ons listed in dev updates list now will be set to dev channel.

Alternative:

1. Use another list(inside add-on update state) just for recording beta channel updates.
2. If the add-on list ilisted in dev updates list, check if it is also recorded in beta updates list, and if yes, set update channel to beta, otherwise dev.
3. Settings UI is same as above.

While the second option is simpler to implement, the first implementation option is more flexible and future proof to prepare for cases where nonstandard prerelease channels are introduced by add-on authors. This change will e part of next stable Add-on Updater release, either in April or when add-on store update source leaves experimental status, whichever happens earlier.

Thanks.

**Comment by ChrisDuffley** [comment]
Hi @josephsl,
I agree with the first option as this is definitely based on context/enabled status rather than having to make yet another list to be keeping track of.

Thanks.

**Comment by josephsl** [comment]
Hi,

In the end, the new key will be called devUpdateChannels to keep it in sync with devUpdates list and to acknowledge the history of Add-on Updater. The hardest part to implement is the actual update check mechanism changes as there places where add-on update channels are selected based on prerelease flag status from Add-on Updater settings panel, but it might be easier than the actual channel selection UI after all (on track for 23.04 release).

Thanks.
