### ISSUE TITLE
Reloading the add-ons duplicate the menu item

### ISSUE THREAD

**Issue by CyrilleB79** [josephsl/addonUpdater#21]
### STR
* Press NVDA+control+F3 to reload add-ons
* Look in NVDA menu -> Tools

### Actual
The add-on updater menu item is duplicated

### Expected

Only one menu item

**Comment by josephsl** [comment]
Hi, cause: aggressive NVDA 2023.2/add-on store detection. I will comment out the relevant code in terminate method in Add-on Updater 23.08.4 (this weekend). Thanks.

**Comment by josephsl** [comment]
Hi,

Resolved in 23.08.4. Thanks.
