### ISSUE TITLE
Add-on build process fails

### ISSUE THREAD

**Issue by lukaszgo1** [josephsl/addonUpdater#5]
After executing scons inn the top directory of the repo I got:
```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Copy("addon\doc\en\readme.md", "readme.md")
Generating addon\doc\en\readme.html
Copy("addon\doc\style.css", "style.css")
Compiling translation addon\locale\ar\LC_MESSAGES\nvda.po
Generating translated manifest addon\locale\ar\manifest.ini
Compiling translation addon\locale\bg\LC_MESSAGES\nvda.po
Generating translated manifest addon\locale\bg\manifest.ini
Compiling translation addon\locale\da\LC_MESSAGES\nvda.po
Generating translated manifest addon\locale\da\manifest.ini
Compiling translation addon\locale\de\LC_MESSAGES\nvda.po
Generating translated manifest addon\locale\de\manifest.ini
Compiling translation addon\locale\es\LC_MESSAGES\nvda.po
Generating translated manifest addon\locale\es\manifest.ini
Compiling translation addon\locale\fa\LC_MESSAGES\nvda.po
Generating translated manifest addon\locale\fa\manifest.ini
Compiling translation addon\locale\fi\LC_MESSAGES\nvda.po
Generating translated manifest addon\locale\fi\manifest.ini
Compiling translation addon\locale\fr\LC_MESSAGES\nvda.po
Generating translated manifest addon\locale\fr\manifest.ini
Compiling translation addon\locale\gl\LC_MESSAGES\nvda.po
Generating translated manifest addon\locale\gl\manifest.ini
Compiling translation addon\locale\he\LC_MESSAGES\nvda.po
Generating translated manifest addon\locale\he\manifest.ini
Compiling translation addon\locale\hi\LC_MESSAGES\nvda.po
Generating translated manifest addon\locale\hi\manifest.ini
Compiling translation addon\locale\hr\LC_MESSAGES\nvda.po
Generating translated manifest addon\locale\hr\manifest.ini
Compiling translation addon\locale\hu\LC_MESSAGES\nvda.po
Generating translated manifest addon\locale\hu\manifest.ini
Compiling translation addon\locale\it\LC_MESSAGES\nvda.po
Generating translated manifest addon\locale\it\manifest.ini
Compiling translation addon\locale\ko\LC_MESSAGES\nvda.po
Generating translated manifest addon\locale\ko\manifest.ini
scons: *** [addon\locale\nl\LC_MESSAGES\nvda.mo] Source `addon\locale\nl\LC_MESSAGES\nvda.po' not found, needed by target `addon\locale\nl\LC_MESSAGES\nvda.mo'.
scons: building terminated because of errors.

(addons) D:\my_repos\addonUpdater>
```

**Comment by josephsl** [comment]
Hi, ultimately this is caused by wrong directory being used to house po files. I’ve been working around this by using a custom script to copy po files to the correct location and then running SCons after that. It is a bit risky to add nl/LC_MESSAGES/nvda.po as it can introduce conflicts to translations workflow (I can try). Thanks.

**Comment by lukaszgo1** [comment]
Rather than working that around with a script I feel it would be more useful to simply use proper directory for *.po files if at all possible. How  you've ended up in this strange situation - as far as I know no other add-on suffers from this problem??

**Comment by josephsl** [comment]
Hi, I think this has to do with the add-on name check in translations workflow (I know, I and others keep saying that we need to fundamentally change how the workflow works). CC @feerrenrut as this is a critical problem. Thanks.

**Comment by feerrenrut** [comment]
@josephsl could you elaborate on what the problem is here, and what you think is the solution?

**Comment by josephsl** [comment]
Hi, for Add-on Updater, l10n data ends up in locale/lang/add-ons/LC_MESSAGES/nvda.po instead of locale/land/LC_MESSAGES/nvda.po. Thanks.

**Comment by feerrenrut** [comment]
As part of which process?

**Comment by josephsl** [comment]
Hi, I suspect svn2addon for Add-on Updater. Thanks.

**Comment by feerrenrut** [comment]
>Hi, for Add-on Updater, l10n data ends up in locale/lang/add-ons/LC_MESSAGES/nvda.po instead of locale/land/LC_MESSAGES/nvda.po. Thanks.

Are you sure these two paths were typed correctly?

I think you'll need to explain this in more detail. What is different for this addon compared to the rest? Surely this a problem with the build process specific to this addon?

**Comment by josephsl** [comment]
Hi, yes the locale folders are correct. This issue does not happen with other add-ons. Add-on Updater’s SConstruct file is the same one used in other add-ons. Thanks.

**Comment by feerrenrut** [comment]
It looks like there is simply a missing po file for lang 'nl'. You might want to look at when / why it got removed?

**Comment by feerrenrut** [comment]
Perhaps the translator doesn't want to translate this addon anymore?

**Comment by josephsl** [comment]
Hi, actually, more translators would like to translate this add-on. Thanks.

**Comment by josephsl** [comment]
Hi, I’ve added locale/lang/LC_MESSAGES/nvda.po manually in the past but the translations workflow encountered conflicts with several files, therefore it was manually resolved. I’d prefer not to go through it again. Thanks.

**Comment by lukaszgo1** [comment]
The issue is solved - my apologies for not closing it earlier. I  see no point in keeping it open as latest Main can build successfully on my machine.
